#!/usr/bin/env bash
# 06-cron-setup.sh — install heartbeat-patrol + 4 maintainer crons + Hermes
# daily-study cron.
#
# Each cron prompts the agent to call heartbeat-patrol FIRST (before doing its
# task), so the heartbeat lands even if the LLM hits turn-limit. Heartbeat-
# patrol then deterministically reads peer heartbeats and Telegram-alerts via
# the configured bot if any peer is stale beyond interval+grace.
#
# The Hermes-side cron (openclaw-daily-study) runs in Hermes's own scheduler
# rather than OpenClaw cron, because Hermes's shell tool is chroot-jailed and
# can only write its heartbeat via filesystem_write — the prompt instructs it
# accordingly.
#
# Idempotent.

set -euo pipefail
export PATH="$HOME/.local/bin:$PATH"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "$SCRIPT_DIR/lib/common.sh"
load_config

OUT_DIR="$REPO_ROOT/.render-cache"
SUBAGENT_NAME="hermes-maintainer"

section "Install heartbeat-patrol + cron jobs"

command -v openclaw >/dev/null 2>&1 || die "openclaw CLI not found"
command -v hermes >/dev/null 2>&1   || die "hermes CLI not found — run 03 first"
command -v jq >/dev/null 2>&1       || die "jq required"

# Confirm subagent registered
if ! openclaw agents list --json 2>/dev/null | jq -e --arg n "$SUBAGENT_NAME" \
        '(.agents // []) | map(.id // .name) | index($n)' >/dev/null 2>&1; then
    if ! openclaw agents list 2>/dev/null | grep -qE "^- ${SUBAGENT_NAME}\b"; then
        die "Subagent $SUBAGENT_NAME not registered — run 05 first"
    fi
fi

emit_journal_event deploy_cron_setup_started ""

# ---------------------------------------------------------------------------
# Step 0: Install heartbeat-patrol script + alert config
# ---------------------------------------------------------------------------
HB_SCRIPT_SRC="$REPO_ROOT/lib/heartbeat-patrol.sh"
HB_SCRIPT_DST="$HOME/.local/bin/heartbeat-patrol"
HB_ENV_LIVE="$HOME/.config/heartbeat-patrol.env"
HB_DIR_OPENCLAW="$WORKSPACE_DIR/heartbeats"
HB_DIR_HERMES="$HOME/.hermes/heartbeats"

mkdir -p "$HOME/.local/bin" "$HOME/.config" "$HB_DIR_OPENCLAW" "$HB_DIR_HERMES" \
         "$WORKSPACE_DIR/upgrade-packs/inbox"

[ -f "$HB_SCRIPT_SRC" ] || die "Missing $HB_SCRIPT_SRC"

if [ -f "$HB_SCRIPT_DST" ] && cmp -s "$HB_SCRIPT_SRC" "$HB_SCRIPT_DST"; then
    info "heartbeat-patrol script unchanged"
else
    cp "$HB_SCRIPT_SRC" "$HB_SCRIPT_DST"
    chmod 755 "$HB_SCRIPT_DST"
    ok "heartbeat-patrol installed at $HB_SCRIPT_DST"
fi

# Render alert config from machine.env (chmod 600).
# Skip if user already has a richer version or token is empty.
if [ -n "${HEARTBEAT_PATROL_BOT_TOKEN:-}" ] && [ -n "${HEARTBEAT_PATROL_CHAT_ID:-}" ]; then
    cat > "$HB_ENV_LIVE" <<EOF
# heartbeat-patrol.env — generated by scripts/06-cron-setup.sh
TELEGRAM_BOT_TOKEN=${HEARTBEAT_PATROL_BOT_TOKEN}
TELEGRAM_CHAT_ID=${HEARTBEAT_PATROL_CHAT_ID}
TELEGRAM_PROXY=${HEARTBEAT_PATROL_PROXY}
EOF
    chmod 600 "$HB_ENV_LIVE"
    ok "heartbeat-patrol.env written ($HB_ENV_LIVE, chmod 600)"
else
    warn "HEARTBEAT_PATROL_BOT_TOKEN / CHAT_ID empty in machine.env"
    warn "  Cross-patrol will log alerts to file but cannot push Telegram."
fi

# Seed heartbeats so first patrol does not false-positive.
seed_heartbeat_if_missing() {
    local job="$1" interval="$2" grace="$3" dir="$4"
    local f="$dir/$job.last"
    if [ ! -f "$f" ]; then
        echo "$(date -Iseconds) interval=${interval}h grace=${grace}h job=$job" > "$f"
        info "  seeded $job"
    fi
}
info "Seeding heartbeats (only if missing)..."
seed_heartbeat_if_missing hermes_daily_doctor      24  6  "$HB_DIR_OPENCLAW"
seed_heartbeat_if_missing hermes_upstream_watch    24  6  "$HB_DIR_OPENCLAW"
seed_heartbeat_if_missing hermes_weekly_review     168 24 "$HB_DIR_OPENCLAW"
seed_heartbeat_if_missing hermes_monthly_compress  720 72 "$HB_DIR_OPENCLAW"
seed_heartbeat_if_missing hermes_daily_study       24  6  "$HB_DIR_HERMES"

ok "heartbeat infrastructure ready"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

heartbeat_prefix_for() {
    local jobname="$1"
    printf 'STEP 1 - FIRST, before any other work, run exactly once:\n  %s/.local/bin/heartbeat-patrol --self %s\nThis writes %s/.openclaw/workspace/heartbeats/%s.last and patrols peer cron jobs. The script sends a Telegram alert via the configured bot only if any peer is stale beyond its interval+grace. Deterministic; just invoke it before doing anything else.\n\nSTEP 2 - ' \
        "$HOME" "$jobname" "$HOME" "$jobname"
}

SUMMARY_TAIL=" When summarizing what you did, list only the positive actions you took (files written, events emitted, tools invoked). Avoid enumerating things you did not do — the OpenClaw cron post-run classifier flags denial phrases as errors."

job_id_by_name() {
    local name="$1" ids first
    ids=$(openclaw cron list --json 2>/dev/null \
            | jq -r --arg n "$name" '.jobs[]? | select(.name == $n) | .id' \
            || true)
    first="${ids%%$'\n'*}"
    printf '%s' "$first"
}

remove_cron_by_name() {
    # Loop until no jobs by this name remain. job_id_by_name returns just
    # the first match; if pre-existing duplicates exist (from a botched
    # earlier run, or operator-side `cron add` collisions), removing once
    # would leak the rest as orphans.
    local name="$1" id
    while id=$(job_id_by_name "$name"); [ -n "$id" ]; do
        info "  removing existing '$name' (id=$id)"
        openclaw cron rm "$id" >/dev/null 2>&1 || die "could not remove $name"
    done
}

add_cron_isolated_for_maintainer() {
    local name="$1" cron_expr="$2" message="$3"
    info "Adding cron: $name [$cron_expr ${TZ_NAME}]"
    if openclaw cron add \
        --name "$name" \
        --cron "$cron_expr" \
        --tz "$TZ_NAME" \
        --session isolated \
        --agent "$SUBAGENT_NAME" \
        --message "$message" \
        --no-deliver \
        --light-context >/dev/null 2>&1; then
        :
    else
        warn "  --light-context unsupported, retrying without"
        openclaw cron add \
            --name "$name" \
            --cron "$cron_expr" \
            --tz "$TZ_NAME" \
            --session isolated \
            --agent "$SUBAGENT_NAME" \
            --message "$message" \
            --no-deliver \
            || die "openclaw cron add failed for '$name'"
    fi
}

# ---------------------------------------------------------------------------
# 4 maintainer crons
# ---------------------------------------------------------------------------

remove_cron_by_name "hermes_daily_doctor"
add_cron_isolated_for_maintainer \
    "hermes_daily_doctor" \
    "$CRON_DAILY_DOCTOR" \
    "$(heartbeat_prefix_for hermes_daily_doctor)Run \`hermes doctor\` from your shell. Append the one-line result to ~/hermes-maintainer/.openclaw-ws/MACHINE_LOG.md. If non-OK, write a study-notes/\$(date +%Y-%m-%d)-hermes-doctor-issues.md and emit a hermes_doctor_report journal event with issues_found > 0. Otherwise emit one with issues_found = 0. Updates are out-of-scope for this job; the operator decides them manually.${SUMMARY_TAIL}"

remove_cron_by_name "hermes_upstream_watch"
add_cron_isolated_for_maintainer \
    "hermes_upstream_watch" \
    "$CRON_UPSTREAM_WATCH" \
    "$(heartbeat_prefix_for hermes_upstream_watch)Check NousResearch/hermes-agent for releases newer than the version in ~/.openclaw/workspace/baseline/baseline.policy.yaml \`known_good.hermes_version\`. Use \`gh release list --repo NousResearch/hermes-agent --limit 5\`. If a new release is found: read its notes via \`gh release view\`, write study-notes/\$(date +%Y-%m-%d)-hermes-vX.Y.Z-release.md describing breaking changes (especially memory/SOUL schema) and whether \`hermes update\` looks safe to run on this host. Updates are out-of-scope for this job; surface the recommendation as journal event \`hermes_release_review_pending\` so the operator can decide manually.${SUMMARY_TAIL}"

remove_cron_by_name "hermes_weekly_review"
add_cron_isolated_for_maintainer \
    "hermes_weekly_review" \
    "$CRON_WEEKLY_REVIEW" \
    "$(heartbeat_prefix_for hermes_weekly_review)Run \`hermes -p openclaw-evolution insights --days 7\` (top-level shell command, NOT the in-chat /insights — both produce similar output but the shell form is cron-safe). Then write a weekly review at study-notes/\$(date +%Y-%m-%d)-weekly-review.md covering: (a) what the openclaw-evolution profile worked on this week (insights output + ~/.hermes/sessions/openclaw-evolution), (b) any upgrade-packs proposed and journal status, (c) drift signals or notable SOUL changes, (d) resource use (du -sh ~/.hermes), (e) anything the operator should look at. Also regenerate the three summary files Hermes reads (baseline-summary-for-hermes.md, mission-summary-for-hermes.md, hermes-permissions-summary.md) under ~/hermes-maintainer/.openclaw-ws/study-notes/. Append a weekly_review event to journal. Hermes state is out-of-scope for this job; this is read-only review work.${SUMMARY_TAIL}"

remove_cron_by_name "hermes_monthly_compress"
add_cron_isolated_for_maintainer \
    "hermes_monthly_compress" \
    "$CRON_MONTHLY_COMPRESS" \
    "$(heartbeat_prefix_for hermes_monthly_compress)Compact session memory by running the /compress slash command in your own session. The shell-form alternative is \`hermes -p openclaw-evolution -z '/compress'\` (the -z flag runs a single message non-interactively). Note before/after sizes (du -sh ~/.hermes/sessions/openclaw-evolution) in MACHINE_LOG.md. Emit a journal event with both sizes.${SUMMARY_TAIL}"

# ---------------------------------------------------------------------------
# Hermes-side daily-study cron (uses Hermes scheduler, not OpenClaw)
# ---------------------------------------------------------------------------
section "Register Hermes daily-study cron"

HERMES_PROMPT_FILE="$OUT_DIR/hermes-daily-study-prompt.txt"
[ -f "$HERMES_PROMPT_FILE" ] || die "Missing $HERMES_PROMPT_FILE — run 01-render.sh"

# Remove any existing Hermes-side job by the same name. hermes cron list is
# human-formatted; parse for the canonical 12-hex-char job ID. Loop in case
# pre-existing duplicates exist.
while
    EXISTING_HERMES_JOB=$(hermes -p openclaw-evolution cron list 2>/dev/null \
        | awk '/openclaw-daily-study/{found=1; next} found && /^  [0-9a-f]{12}\b/{print $1; exit}' \
        | head -1)
    [ -z "$EXISTING_HERMES_JOB" ] && \
        EXISTING_HERMES_JOB=$(hermes -p openclaw-evolution cron list 2>/dev/null \
            | grep -B2 'openclaw-daily-study' | grep -oE '\b[0-9a-f]{12}\b' | head -1 || true)
    [ -n "${EXISTING_HERMES_JOB:-}" ]
do
    info "Removing existing Hermes cron $EXISTING_HERMES_JOB"
    hermes -p openclaw-evolution cron rm "$EXISTING_HERMES_JOB" >/dev/null 2>&1 || true
done

if hermes -p openclaw-evolution cron create \
    --name openclaw-daily-study \
    "$CRON_HERMES_DAILY_STUDY_UTC" \
    "$(cat "$HERMES_PROMPT_FILE")" >/dev/null 2>&1; then
    ok "Hermes daily-study cron registered ($CRON_HERMES_DAILY_STUDY_UTC UTC)"
else
    warn "Hermes daily-study cron registration failed — re-run after fixing"
fi

ok "All cron jobs registered"

echo
info "Active cron jobs (filtered to ours):"
openclaw cron list --json 2>/dev/null \
    | jq -r '.jobs[]? | select(.name | startswith("hermes_")) | "  \(.name)  schedule=\(.schedule.expr // "?") \(.schedule.tz // "")  agent=\(.agentId // "?")  id=\(.id)"' \
    || warn "could not parse cron list --json output"
echo
hermes -p openclaw-evolution cron list 2>/dev/null | head -10 || true

emit_journal_event deploy_cron_setup_completed "jobs=5"
ok "Step 06 complete. Proceed to 07-smoke-test.sh."
