#!/usr/bin/env bash
# 09-talk-helpers.sh — generate `talk-<agent>` ACP wrapper scripts.
#
# Discovers registered OpenClaw agents and creates one wrapper per agent in
# ~/.local/bin/talk-<name>, plus a `talk-hermes` wrapper for Hermes itself.
#
# Idempotent.

set -euo pipefail
export PATH="$HOME/.local/bin:$PATH"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "$SCRIPT_DIR/lib/common.sh"

section "Generate talk-* ACP shortcuts"

BIN_DIR="$HOME/.local/bin"
GENERATED_DIR="$HOME/.local/share/openclaw-talk-helpers"
mkdir -p "$BIN_DIR" "$GENERATED_DIR"

write_acp_helper() {
    local cmd_name="$1" agent_id="$2"
    local script_path="$GENERATED_DIR/$cmd_name.sh"
    cat > "$script_path" <<HELPER_EOF
#!/usr/bin/env bash
# Auto-generated by openclaw-hermes-watcher 09-talk-helpers.sh
exec openclaw acp --session "agent:${agent_id}:main" "\$@"
HELPER_EOF
    chmod +x "$script_path"
    ln -sf "$script_path" "$BIN_DIR/$cmd_name"
    ok "  $cmd_name -> $agent_id"
}

write_hermes_helper() {
    local script_path="$GENERATED_DIR/talk-hermes.sh"
    cat > "$script_path" <<'HELPER_EOF'
#!/usr/bin/env bash
# Auto-generated by openclaw-hermes-watcher 09-talk-helpers.sh
# Open an interactive Hermes session in the openclaw-evolution profile.
exec hermes -p openclaw-evolution "$@"
HELPER_EOF
    chmod +x "$script_path"
    ln -sf "$script_path" "$BIN_DIR/talk-hermes"
    ok "  talk-hermes -> hermes -p openclaw-evolution"
}

info "Generating talk-* wrappers in $GENERATED_DIR and symlinking to $BIN_DIR..."

# Discover OpenClaw agents via openclaw agents list --json (with text fallback).
agents_json=$(openclaw agents list --json 2>/dev/null || echo '{}')
agent_names=$(echo "$agents_json" | jq -r '.agents // [] | map(.name // .id) | .[]' 2>/dev/null || true)

if [ -z "$agent_names" ]; then
    warn "Could not parse 'openclaw agents list --json' — falling back to defaults"
    agent_names="main
hermes-maintainer"
fi

while IFS= read -r agent; do
    [ -z "$agent" ] && continue
    case "$agent" in
        main)              write_acp_helper "talk-main"        "$agent" ;;
        hermes-maintainer) write_acp_helper "talk-maintainer"  "$agent" ;;
        *)                 write_acp_helper "talk-${agent}"    "$agent" ;;
    esac
done <<< "$agent_names"

# Hermes itself (NOT OpenClaw)
if command -v hermes >/dev/null 2>&1; then
    write_hermes_helper
else
    warn "  talk-hermes skipped (hermes CLI not on PATH)"
fi

echo
info "Installed shortcuts:"
ls -la "$BIN_DIR"/talk-* 2>/dev/null | awk '{print "  " $NF " -> " $(NF-2)}' || true
echo
ok "Done. Try: talk-maintainer (or talk-main, talk-hermes, etc.)"
info "These wrappers pass through any extra args:"
echo "  talk-hermes -z '/usage'    # one-shot slash command"
echo "  talk-maintainer --help     # show ACP options"
